name: Run Azure Login with OpenID Connect
on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: 'Run Azure CLI commands'
      run: |
          az version